### PR TITLE
Fix test suites dashboard missing empty state views

### PR DESCRIPTION
**Pull request by ryanjduffy**
Adds messaging and loading indicators when filtering or selecting items

https://www.loom.com/share/a2f76d875f5a42fa9cc6390abbf58c3a

### CODE REVIEW

**Comment by callingmedic911** [comment]
That loom's of wrong tab? Or it's either frozen 😅

**Comment by ryanjduffy** [comment]
> That loom's of wrong tab? Or it's either frozen 😅

Dunno ... I'll check it tomorrow

**Comment by ryanjduffy** [comment]
Fixed the loom. Also added indeterminate loader support to the test details view (which required a bit of refactoring to memoize the return value of `useTest`).

**Review by jonbell-lot23 — APPROVED** [review]

**Comment by jaril** [comment]
@ryanjduffy just pushed a lint fix!

**Comment by callingmedic911** [comment]
This looks good to me. Ryan is out for a few days, so I'm going to resolve the conflict and get this in, otherwise there may be more conflict to resolve after a week. 😅 @ryanjduffy feel free to followup on this if we missed anything.

**Review by callingmedic911 — APPROVED** [review]

**Pull request merged**
