### PR TITLE
Don't throw on Analysis errors (FE-690)

### PR DESCRIPTION
**Pull request by hbenl**

### CODE REVIEW

**Comment by markerikson** [comment]
I think this seems reasonable conceptually - what's the net behavior difference at runtime?

**Review by markerikson — APPROVED** [review]

**Comment by jcmorrow** [comment]
> I think this seems reasonable conceptually - what's the net behavior difference at runtime?


@markerikson I think this is to make it less likely that the console error boundary gets triggered and causes the whole thing to turn into "Oops, sorry, something crashed"

**Comment by markerikson** [comment]
Sure, that seems like a good thing :)

**Comment by bvaughn** [comment]
What's the UX of this change? (What actually happens in the Console?)

Would have probably been nice to see a video or something.

**Pull request merged**
