### PR TITLE
Dropdown/ContextMenu refactor 2 

### LINKED ISSUE #6909: Dropdown interaction issues
**Description:**

Dropdown have a few issues with a11y,

* Focus doesn't return to the button on select item
* Can't close on scape
* Can't navigate on options with arrows keys

**Steps to Reproduce:**

Try to use a dropdown with keyboard 

**Expected Result:**

Users can use a dropdown only with the keyboard

**Additional Context:**

https://user-images.githubusercontent.com/9127504/169709488-dc6dcdf6-3ed6-4cec-b1c4-f2eee50cf73e.mp4

### PR DESCRIPTION
**Pull request by yeion7**
fix #6909 

I figured out that actually dropdown is using `@headlessui/react`, that have most of the required keyboard interactions build out-of-the-box, the issue is the way that component is being used

In this PR I'm proposing a new Dropdown API

```
<Dropdown trigger={<Icon ... />}>
  <DropdownItem>Option 1</DropdownItem>
  <DropdownItem>Option 1</DropdownItem>
</Dropdown>
```

* Dropdown supports keyboard interactions ([more](https://headlessui.dev/react/menu#keyboard-interaction))
* Dropdown list is render in a portal always
* All the Dropdown positioning is handle by `@popperjs/core`

This is removing `PortalDropdown`, and `shared/Dropdown`, in favor of `Library/LibraryDropdown`

https://user-images.githubusercontent.com/9127504/169709870-3697ab46-c13c-4089-8976-52402ec0d551.mp4

### CODE REVIEW

**Comment by yeion7** [comment]
@bvaughn I was able to reproduce the original issue with this PR, and I fixed it

**Comment by ryota-murakami** [comment]
@yeion7 Thank you for awesome PR!
I think e2e Test is most shining such as refactor, so I really want to fill testcase with original [Playwrght](https://playwright.dev/) for UI interaction except Debugger/Recoerder Core(I mean replay.io/playright field)

**Comment by jasonLaster** [comment]
@yeion7 seeing some merge conflicts

**Comment by bvaughn** [comment]
Sorry for not reviewing this faster, @yeion7. Looks like it now has some conflicts. Would you be willing to rebase and then ping me and I can take a look? If you're too busy, that's understandable.

**Pull request closed without merging**
