### PR TITLE
FE-348: Update Next to 12.2 and use SWC instead of Babel

### PR DESCRIPTION
**Pull request by markerikson**
This PR:

- Adds the ability to run a bundle size analysis on our Next builds
- Updates Next to 12.2: https://nextjs.org/blog/next-12-2
  - Fixed a few new TS errors that popped up where some query params could be undefined apparently
- Updates our build config to use Next's built-in SWC support for compiling JS instead of Babel, and customizes the `browserslist` setting to continue targeting `"chrome 95"` instead of the default list of browsers

Per local build checks, I've confirmed that SWC + the default browsers _adds_ about 40KB per bundle on top of Babel (where we have about 550KB as a baseline), but SWC + `"chrome 95"` _drops_ 8KB. So, a very small win for bundle size.

Compile times in dev seem to drop from 40s for `/` and 26s for `/recording`, to 20s and 13s respectively.

### CODE REVIEW

**Review by bvaughn — APPROVED** [review]
👍🏼

**Comment by markerikson** [comment]
While not actually changes in the PR itself, I'm trying out some alternate settings with Vercel to see if I can get it to do a better job of caching Yarn's `.yarn/cache` folder and our root `node_modules`, by setting `ENABLE_ROOT_PATH_BUILD_CACH=1` as a Vercel env var, and changing the install command to be `YARN_CACHE_FOLDER=./.next/cache/yarn-cache yarn install`:

- https://github.com/vercel/vercel/discussions/4223#discussioncomment-861536
- https://github.com/vercel/community/discussions/222#discussioncomment-2036114

**Comment by markerikson** [comment]
Also: this PR does _not_ update Jest to use SWC, or remove any of our Babel deps. We oughta try that later.

**Comment by markerikson** [comment]
Success!

```
Looking up build cache...
Build cache downloaded [445.98 MB]: 24700.046ms
Running "install" command: `YARN_CACHE_FOLDER=./.next/cache/yarn-cache yarn install`...
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 679ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 2374 packages were already cached
➤ YN0000: └ Completed in 1s 541ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 9s 533ms
```

**Pull request merged**
