### PR TITLE
Elements panel support basic and advanced search UX

### PR DESCRIPTION
**Pull request by bvaughn**
Search now defaults to basic (what you see) but can be toggled to "advanced" (how Chrome's Elements panel works). User preference is remembered in local storage.

https://github.com/replayio/devtools/assets/29597/14a51184-d8f4-42ba-a72f-99f688fedca1

New unit tests and e2e test included.

### CODE REVIEW

**Review by jasonLaster — COMMENTED** [review]
Love this feature. Lets add an E2E test for it before it lands

**Comment by bvaughn** [comment]
I added unit tests for this, but new e2e tests are difficult to add for Chromium because of how broken it is currently (see the baby steps progress I'm trying to make on #10008 for example)

**Comment by bvaughn** [comment]
Thanks for pushing for the e2e test. It uncovered an awkward edge case that is now handled better. 👍🏼

**Comment by bvaughn** [comment]
All e2e tests pass on [the latest run](https://app.replay.io/team/dzowNDAyOGMwYS05ZjM1LTQ2ZjktYTkwYi1jNzJkMTIzNzUxOTI=/runs/1b0340b5-748e-49d6-844d-4b7998837075?param=dzowNDAyOGMwYS05ZjM1LTQ2ZjktYTkwYi1jNzJkMTIzNzUxOTI%3D&param=runs&param=77ea07fb-5cae-449d-92e2-c97623846ffe)
Screenshot 2023-12-19 at 12 20 56 PM

**Review by markerikson — APPROVED** [review]

**Pull request merged**
