### PR TITLE
Add bigger click target for code comments

### PR DESCRIPTION
**Pull request by jonbell-lot23**
**Summary**

When you're in DevTools and you click on a comment, we should load the line of code in Source Viewer. Before this change, we only took you to code when you clicked the small code callout, but now it's the whole region.

image

### CODE REVIEW

**Comment by jonbell-lot23** [comment]
Loom demo: https://www.loom.com/share/c3c12c91df724607aec44a842bd0c168

Before/after showing off the visual polish (notice that the code callout is using the same color as the current line of code)
Click on comment

**Comment by jonbell-lot23** [comment]
Stay tuned @ryanjduffy , @jasonLaster wonders if we can remove the filename and line number from the blurb and put it behind a hover instead. I'll be working on that to see how it feels.

**Comment by jonbell-lot23** [comment]
Ok, now we have tooltips and this should be ready for review. here's a quick Loom of the tooltip behaviour: https://www.loom.com/share/8dd2aeec8a41485980e5c0626ef229b4

**Review by jasonLaster — APPROVED** [review]
Looks great to me

**Pull request merged**
