### PR TITLE
Recover from ObjectPreview 'Could not find object with id' error

### PR DESCRIPTION
**Pull request by bvaughn**
Doesn't feel great, but fixes a potential "data not loaded" condition for the Object Inspector.

### CODE REVIEW

**Review by markerikson — APPROVED** [review]
Interesting. Worth a shot once this passes.

**Comment by bvaughn** [comment]
I have an alternate idea for this that I'm going to try (why this one's still a draft).

**Comment by bvaughn** [comment]
This might be a better fix.

**Comment by bvaughn** [comment]
Why is Yarn build failing with a TypeScript error

**Comment by bvaughn** [comment]
Looks like it was a funky whitespace character in `pause.ts` which I have hopefully removed but I dunno

**Review by markerikson — APPROVED** [review]

**Comment by bvaughn** [comment]
What the hell is going wrong with TypeScript here.

**Comment by bvaughn** [comment]
Same bizarre problem with #7454. I can run the `yarn build` command locally without any trouble though.

**Comment by bvaughn** [comment]
Closing in favor of #7454 which I was able to actually get Vercel to build 😮‍💨

**Pull request closed without merging**
