### PR TITLE
Update RDT fork for 2024-07

### PR DESCRIPTION
**Pull request by markerikson**
This PR:

- Updates the RDT built bundle with changes for the last month, built from [replayio/react@`57ff604` (#15)](https://github.com/replayio/react/pull/15/commits/57ff60421100516422a1de647725eb3779fe4117) 

References with reviewable changes:

- Upstream RDT changes: https://github.com/replayio/react/pull/16
- Flow/Lint fixes: https://github.com/replayio/react/pull/17

### CODE REVIEW

**Comment by markerikson** [comment]
Looks like we lost the `DEVTOOLS_PLACEHOLDER` variable somewhere in the merge / rebase process.

**Comment by markerikson** [comment]
Well, this is clearly busted somehow.

It _may_ have something to do with the comments I added to `react_backend_compact.js`, but I'm still trying to sort that out locally :(

**Review by bvaughn — APPROVED** [review]
Gonna stamp to unblock even though CI is busted

**Comment by markerikson** [comment]
For posterity's sake, what I learned:

Our code:

```ts
const rdtInjectionExpression = `(${installReactDevToolsIntoPause})()`
  .replace("INSTALL_HOOK_PLACEHOLDER", `(${injectGlobalHookSource})`)
  .replace("DEVTOOLS_PLACEHOLDER", `(${reactDevtoolsBackendSource})`);

console.log("RDT expression: ", rdtInjectionExpression);
```

Snipped output from the minified RDT bundle:

```js
=t)return null;const{_debugOwner:n,stateNode:r,key:o,memoizedProps:i,memoizedState:s,dependencies:l,tag:a,type:u}=t,c=yt(t),f=!(a!==I&&a!==ne&&a!==C||!s&&!l),d=!f&&a!==w,h=g(u);let y=!1,v=null;if(a===_||a===I||a===R||a===A||a===F||a===L||a===C||a===ne)y=!0,r&&null!=r.context&&(c===DEVTOOLS_PLACEHOLDER&!u.contextTypes&&!u.contextType||(v=r.context));else if(h!==$e&&h!==ze||void 0===u._context&&u.Provider===u){if(h===Je){const e=u._context;v=e._currentValue||null;let n=t.return;for(;null!==n;){const t=n.type;if(g(t)===ze&&t===e){v=n.memoizedProps.value;break
```

prettified minified code:

```js
            (y = !0),
              r &&
                null != r.context &&
                ((c === $ && !u.contextTypes && !u.contextType) ||
                  (v = r.context));
```

so that became:

```ts
(c===DEVTOOLS_PLACEHOLDER&!u.contextTypes&&
```

**IT'S REPLACING THE _DOLLAR SIGN_ WITH THE _SEARCH TEXT?!?!?!?!?_**

more specifically:

- The minifier for this build of the RDT is spitting out a `$` as a minified variable name
- that's fine-ish if the code still has whitespace
= but with whitespace stripped, `c == $ && whatever` becomes `c==$&&`
- and `$&` is a magic replacement token

and the answer is to pass a _function_ as the replacer rather than the string directly:

```ts
const rdtInjectionExpression = `(${installReactDevToolsIntoPause})()`
  .replace("INSTALL_HOOK_PLACEHOLDER", () => `(${injectGlobalHookSource})`)
  .replace("DEVTOOLS_PLACEHOLDER2", () => `(${reactDevtoolsBackendSource})`);
```

because that apparently ignores special characters:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_function_as_the_replacement

**Pull request merged**
