### PR TITLE
Auto-scroll to the last failed test step

### PR DESCRIPTION
**Pull request by hbenl**
I also updated the logic for auto-selecting the failed step to use the *last* failed step if there is more than one.

### CODE REVIEW

**Review by markerikson — APPROVED** [review]

**Comment by hbenl** [comment]
That test failure is interesting: we are now getting 17 "Anonymous" React components instead of 16. This has nothing to do with this PR, it now also [happens on main](https://app.replay.io/team/dzowNDAyOGMwYS05ZjM1LTQ2ZjktYTkwYi1jNzJkMTIzNzUxOTI=/runs?testRunId=4e422e87-4847-446d-aab6-694b7c9ca632&testId=dHJ0OmE3MTQzZjkyY2EwODUwNmUzMzU4YTJkNTVlOWM5M2YxYWE3ZjEzYzU%3D). I guess this changed when the new RDT bundle was deployed to the backend (note that we have `backend_rerunRoutines` enabled for this test).
I'll update the test.

**Comment by bvaughn** [comment]
> That test failure is interesting: we are now getting 17 "Anonymous" React components instead of 16. 

That's interesting. That didn't fail on Mark's commit to frontend (06b89f444f9630cea0afef4ff67624e3cf84f1aa) so...was it caused by the backend commit (06b89f444f9630cea0afef4ff67624e3cf84f1aa)?

**Comment by hbenl** [comment]
> so...was it caused by the backend commit

I think so (that's why I mentioned `backend_rerunRoutines` - without it I think the backend commit should not have made a difference).

**Comment by bvaughn** [comment]
That seems like a potentially significant weakness in our current sync process

**Comment by markerikson** [comment]
Oh lovely :(

**Pull request merged**
