### PR TITLE
Standardize onboarding visuals

### PR DESCRIPTION
**Pull request by jonbell-lot23**
**Quick summary**

Last week I pushed out  [this PR](https://github.com/replayio/devtools/commit/e8b1caecb15bbe9f4e1960b86e090824cbb71203#diff-08ba8b007c17174535e61a7422566fb3b70c9bada21eb0b464273fef58b78295) but it affected our loading screen. This PR refactors the code enough to commit the original PR without messing up the loading screen.

**Details**
I tracked this refactor [over here in Notion](https://www.notion.so/replayio/Refactoring-our-modals-17be55d6a0e6425ba4ff503fc894fc98?pvs=4). The end result looks like this:

* Standard screens (e.g. our loading screen) still respect themes (instead of hard-coding to dark)
* Onboarding screen are hard-coded to dark
* We have a slightly different treatment for our "welcome" screens than our onboarding screens, but both dark

**Dynamic theme screens such as loading and "ready when you are"**

image
image

**Dark theme "welcome" screens**

image

**Dark theme onboarding screens**

image

**Next steps**

This refactor is a big step forward, but there's still work to do. The main goal here is to address the initial bugs we've uncovered, make the code a bit better, and not mess up the loading screen. Once this goes live, we'll be iterating on this further.

### CODE REVIEW

**Comment by jasonLaster** [comment]
Can you share the other screens along the onboarding journey? For instance, if you go to replay.io/pricing and click create team or org you'll be prompted to create a new team.

--

> **Hello, I'm the Replay Browser** Nice to meet you! I'm going to save you and your team a lot of time

I'd opt for clearer copy that describes the benefits of the Replay Browser.

**Welcome to Replay** Replay lets you record bugs and replay them with time-travel enabled browser DevTools.

**Comment by jonbell-lot23** [comment]
> Can you share the other screens along the onboarding journey? For instance, if you go to replay.io/pricing and click create team or org you'll be prompted to create a new team.

Yup, http://go/nux-slideshow's where the journey is documented. I'll need to update it once these visuals are live, and there are edge cases to add, but that's where it will live.

**Comment by jonbell-lot23** [comment]
> Can you share the other screens along the onboarding journey? For instance, if you go to replay.io/pricing and click create team or org you'll be prompted to create a new team.
> 
> --
> 
> > **Hello, I'm the Replay Browser** Nice to meet you! I'm going to save you and your team a lot of time
> 
> I'd opt for clearer copy that describes the benefits of the Replay Browser.
> 
> **Welcome to Replay** Replay lets you record bugs and replay them with time-travel enabled browser DevTools.

Swapped

**Comment by markerikson** [comment]
Seems like the auth tests all timed out waiting for the page to load, which is... weird. Never got past the loading screen.

**Review by markerikson — APPROVED** [review]

**Comment by jonbell-lot23** [comment]
> Seems like the auth tests all timed out waiting for the page to load, which is... weird. Never got past the loading screen.

Super odd, it's loading for me on the preview link

**Pull request merged**
