### PR TITLE
AvatarImage uses useTooltip hook to show user's names as Replay tooltips

### PR DESCRIPTION
**Pull request by bvaughn**
This finishes out the UI spec in FE-1201 and I think is probably a good general change for anywhere we have a user avatar:

Screen Shot 2023-02-13 at 2 24 24 PM

Screen Shot 2023-02-13 at 2 24 28 PM

cc @jonbell-lot23

### CODE REVIEW

**Comment by jasonLaster** [comment]
Surprised we dont show the tooltip on top. Also - would we show the avatar in the print statements panel when it's yours? Would be surprised if we do

**Comment by jonbell-lot23** [comment]
> Surprised we dont show the tooltip on top. Also - would we show the avatar in the print statements panel when it's yours? Would be surprised if we do

Agree with both points. Can we align to top and make sure your own avatar doesn't show?

**Review by hbenl — APPROVED** [review]

**Comment by bvaughn** [comment]
> Surprised we dont show the tooltip on top.

Why would we? I don't think that was part of a spec anywhere I saw, so we just showed it like a normal tooltip.

> Also - would we show the avatar in the print statements panel when it's yours? Would be surprised if we do

No. The video is from an _anonymous_ account looking at print statements created by my user.

**Comment by bvaughn** [comment]
https://user-images.githubusercontent.com/29597/218746492-88d0b972-7f2a-4def-b150-58404f1173e5.mp4

**Pull request merged**
