### PR TITLE
Replay Next Reconciliation: Core design tokens 

### PR DESCRIPTION
**Pull request by jonbell-lot23**
We started with tabs and nothing broke. So this is a meatier PR following the same approach, and things are still not breaking:

Timeline
Menus
Code Mirror
Breakpoints
Testsuites
Toolbar
Toolbar buttons
Buttons
Accordion headers
Selection
Border color that splits the toolbars/panels/headers.
Icon colors

### CODE REVIEW

**Review by bvaughn — CHANGES_REQUESTED** [review]
Looks like this change broke something.

On `main` (and the previous branch) this is what the Settings dialog looks like in light mode:
Screen Shot 2023-01-05 at 10 35 11 AM

On this branch it looks like this:
Screen Shot 2023-01-05 at 10 35 01 AM

**Comment by jonbell-lot23** [comment]
Found the typo, fixed it, ready for re-review

**Comment by bvaughn** [comment]
Code looks good but the Lint task is failing because of a formatting issue. You can fix this by running: this command in the root directory
```sh
npm run lint
```

**Comment by jonbell-lot23** [comment]
Whoops, lint issue addressed.

(Side note: I see that merging is blocked, but I'm having trouble finding the way to say "resolve issue.")

**Review by bvaughn — APPROVED** [review]

**Pull request merged**
