### PR TITLE
Add "jump to line of code" click target to events panel

### PR DESCRIPTION
**Pull request by jonbell-lot23**
Loom of it in action:
https://www.loom.com/share/c96ffced5e2143e2b59471356905c555

image

image

### CODE REVIEW

**Comment by jasonLaster** [comment]
Pushed some small fixes which will help us get this out the door. For example, let's do the `showToast` thing in a separate PR.

**Comment by jasonLaster** [comment]
Will land this because it's a big step forward and I'd like to have it for 2 demos today. As a follow up

1. some buttons are not formatted
2. Do we want to use more consistent labels for the console / event timeline 
3. I'd prefer when we unfurl to keep the icon in the same place, curious what others think

**Comment by markerikson** [comment]
Another bug: we're showing it on _all_ list items, but that includes "navigation" events. We should only be showing it on click and keypress event list items.

**Comment by jonbell-lot23** [comment]
Filed a new issue here for follow-up: https://linear.app/replay/issue/DES-318/events-follow-up-polish

**Pull request merged**
