### PR TITLE
Use ❌ and ✅ in titles to reflect test result

### PR DESCRIPTION
**Pull request by jonbell-lot23**
image

Addresses https://linear.app/replay/issue/DES-847/replay-test-titles-should-include-a-pass-fail-emoji

### CODE REVIEW

**Comment by jasonLaster** [comment]
I wonder if we should replace the Replay favicon with a test icon? This has the benefit of always being there even with lots of tabs. Also looks nicer.

Should we also address the treatment in the title too or do you think we don't need it if we do the tab? My hunch is that the title still matters because it's in the app, the tab is a bit far to go.

**Comment by jonbell-lot23** [comment]
> I wonder if we should replace the Replay favicon with a test icon? This has the benefit of always being there even with lots of tabs. Also looks nicer.
> 
> Should we also address the treatment in the title too or do you think we don't need it if we do the tab? My hunch is that the title still matters because it's in the app, the tab is a bit far to go.

Good thoughts. I agree that one icon looks nicer than two. But I'm not sure how I feel about logic/branding that says "sometimes we show the Replay icon and sometimes we don't." It feels like it may be a bit too clever and possibly even confusing.

The title is an interesting one. We have a slick feature for hovering over a title to edit it, and right now it's pixel perfect. As soon as we prepend with an emoji, it gets more complicated for users.

--

I think we should ship this as-is to get a quick win, learn things, and iterate from there. Whether we add both ideas, neither of them, or somewhere in between, I think we'll get better instincts for it trying this one for a few days.

**Comment by jonbell-lot23** [comment]
Oh, I meant to talk about the title/tab thing:

To me, this feature addresses a very clear issue: it's hard to tell tabs apart. So I think addressing that is key.

Whereas if we think we can be more clear in the product itself, there are tons of things we can do to make that more clear. It doesn't have to be either/or.

**Comment by jasonLaster** [comment]
Sounds good

**Review by markerikson — APPROVED** [review]

**Pull request merged**
