### PR TITLE
Prevent Earthly from skipping Playwright tests due to caching

### PR DESCRIPTION
**Pull request by bvaughn**
Am I crazy? Is there a better way to do this? 😅

### CODE REVIEW

**Comment by bvaughn** [comment]
No worries 😆 Wouldn't `--push` invalidate _all_ caching? It's nice to get _some_ caching. I just don't want the contents of the tests themselves to be cached.

I don't have a very solid mental model for how this works.

**Comment by jazzdan** [comment]
So `--push` should only prevent caching on `RUN`s that have `--push` applied. All other steps would still be cached

**Comment by bvaughn** [comment]
Isn't that basically the same thing? If we always have to `--push` to ensure we don't get false positives (b'c of caching causing steps to be skipped), and nothing is cached when `--push` is used, then wouldn't we always bypass caching?

The thing I was trying to do with this PR was to only cache-bust the tests themselves.

**Comment by bvaughn** [comment]
Actually it looks like `--push` doesn't work anyway
Screen Shot 2022-08-24 at 2 53 32 PM

**Comment by jazzdan** [comment]
Yeah you're right.

I think the fundamental problem here is that earthly doesn't know anything about the code being tested, what we actually want is to bust the test result cache when any of the code that goes in to running `yarn dev` changes but because all of that is happening outside of earthly there's no way for it to do that.

**Review by jazzdan — APPROVED** [review]

**Comment by jazzdan** [comment]
I _think_ there's a way to achieve earthly knowing about all of the code that goes in to `yarn dev` but each time I've tried to do it I've been thwarted by yarn workspaces weirdness. Maybe we could pair on it at some point? :)

**Comment by bvaughn** [comment]
Gotcha. That's fair. Thanks a bunch for the discussion!

**Pull request merged**
