### PR TITLE
Replace Comment editor and Terminal input(s) with Lexical

### PR DESCRIPTION
**Pull request by bvaughn**
### New code editor:

https://user-images.githubusercontent.com/29597/204943047-a1914eb9-961f-4877-bb87-4cade9e8d95f.mp4

### New comment editor:

https://user-images.githubusercontent.com/29597/204943034-a4486374-a04e-460e-8ce7-a021c8605a81.mp4

Create CommentsPlugin with basic markdown and mentions typeahead.
- [x] Support markdown import for existing GraphQL content
- [x] Support JSON import/export for persisting/editing comments
- [x] Typeahead with mentions (teammate names)
- [x] Support read-only mode for displaying comments
- [x] Add Loom node

Create TerminalPlugin with Lezer based syntax highlighting and code-completion typeahead.
- [x] Format initial text
- [x] Support JSON import/export for persisting log points
- [x] Update text as user types, while preserving cursor/selection (based off of packages/lexical-code/src/CodeHighlighter)
- [x] Typeahead with code suggestions

Follow-up work:
- [x] Enable comment mentions
- [x] Improve serialization (may require GraphQL changes)
- [x] Delete any last lingering traces of Code Mirror 5 and Tip Tap
- [ ] Comment mentions should send email notifications (requires backend changes)

### CODE REVIEW

**Comment by jasonLaster** [comment]
Very cool. Wonder if it makes sense for these plugins to be in their own devtools package for possible publishing down the line? Could also be a good practice for separation of concerns

**Comment by bvaughn** [comment]
Probably need to go over e2e tests and update a few things, but otherwise I think this is ready for some testing and review.

**Comment by bvaughn** [comment]
Rebased. Should be ready for review now.

**Comment by bvaughn** [comment]
Ran all e2e and playwright (screenshot) tests locally and they pass. I assume the CI red Xs are from the backend being flaky, as happens sometimes.

**Comment by bvaughn** [comment]
Looked at the few remaining e2e tests.

The [most recent run of the stacking test](https://app.replay.io/recording/stacking-element-highlighter-selects-the-correct-element-when-they-overlap--72dc9056-f184-455e-8db5-73041c88b8e2?point=55817191230343484926929595113930752&time=17651) def failed because the console never finished loading (as we've been seeing today in a few places).

**Pull request merged**
