### PR TITLE
Move Video toggle button to app toolbar

### PR DESCRIPTION
**Pull request by bvaughn**
- [x] Update `useLocalStorageUserData` to subscribe to changes made to `localStorage` from other places in the React tree
- [x] Move video toggle button into the app toolbar

Kapture 2023-08-30 at 15 27 35

cc @jonbell-lot23

### CODE REVIEW

**Review by markerikson — APPROVED** [review]

**Review by jonbell-lot23 — COMMENTED** [review]
1. I do think keeping the video blue when enabled is an important indicator of set state. This is an opinion, and I won't be surprised if/when others agree, but that's my opinion about that.

2. Can you add a trackEvent for this?

**Comment by jonbell-lot23** [comment]
Lol, missed it by 2 minutes

**Comment by bvaughn** [comment]
> I do think keeping the video blue when enabled is an important indicator of set state. This is an opinion, and I won't be surprised if/when others agree, but that's my opinion about that.

Ah, I misunderstood the mock on the issue. My bad.

**Comment by bvaughn** [comment]
#9661

**Pull request merged**
