### PR TITLE
[DRAFT] Rework recording title input to have better focus / edit behavior

### PR DESCRIPTION
**Pull request by markerikson**
This PR:

- _Mostly_ gets the recording title input to show its border on hover and focus, and be more explicit about when it's editing

Generally, changed it from a contenteditable span to a controlled `<input>`, and tried to make the logic handle saving correctly.  I can see a glitch if you delete the text entirely and hit "Save" - it's reverting back to a title from the underlying recording instead of "Untitled", but this is along the right lines.

Styling / behavior is slightly different than what Jon suggested in FE-911 - it shows an outline on hover, and has a single-click to start editing, instead of a double-click.

### CODE REVIEW

**Comment by jasonLaster** [comment]
Here's some product feedback 
https://www.loom.com/share/63ea66c724604626aa1883e08abd5730

cc @jonbell-lot23

**Comment by jonbell-lot23** [comment]
Hey team! Agreeing with Jason and adding some thoughts:

1. Definitely agree we don't want it full width
2. The border on hover is too bold -- but I do think something on hover is important

Here's what I'd propose:

1. No full width
2. On hover, don't do a border, do a background color (stay tuned next week for the exact variable name)
3. On click, border
4. On second click, enter edit state

It's so uncommon to rename that I think a double-click is a more appropriate level than a single click. It should be a bit harder to get to, because I'd rather it take an extra click than to accidentally capture mis-clicks.

... and that's why I'm referring to highlighting it on hover. It should signal that it is actionable (hover effect) but not be too easy (double-click). If this was more common/desired behaviour, I'd go with a pencil on hover and a single click. But because this feature should be more tucked away, that's why I think this is the best UX.

**Comment by jasonLaster** [comment]
Sounds good. It'd be easy to dismiss this discussions as overkill, but the top left of the app is incredibly visible real estate and these interactions can help give people a positive/negative initial impression.

**Comment by jonbell-lot23** [comment]
Oh I don't think this is overkill at all. This sort of thing is my specialty and I'm happy to see us working on it.

**Comment by bvaughn** [comment]
> 3. On click, border
> 4. On second click, enter edit state

What does a border on click indicate?

For most editable things, I think the focus outline indicates "you can now edit this thing" but in this case, what does it mean?

What if you single click again after you're already in the single clicked state? What if you press Enter?

**Comment by markerikson** [comment]
Just for the record, requiring a multi-single-click sequence to start editing _will_ add to internal complexity of implementation, and wouldn't be my first choice.

**Comment by jonbell-lot23** [comment]
> > 5\. On click, border
> > 6\. On second click, enter edit state
> 
> What does a border on click indicate?
> 
> For most editable things, I think the focus outline indicates "you can now edit this thing" but in this case, what does it mean?
> 
> What if you single click again after you're already in the single clicked state? What if you press Enter?
> 
> > 1. No full width
> 
> Definitely agree with this! 😁

A lot of web and consumer UI is more on the Fischer-Price side of the scale, where hovers and single-clicks do everything you need them to. But you can overdo it, as we did here where we took a very rare action (renaming a Replay) and made it a single click with a huge hit target.

There is precedent for non-80% features being tucked away, and that's what I was going for here. The hover explained actionability, and a second click would get into editing for the people who want to edit.

That said, I need to prioritise my time, so it's fine to go with a single-click here because I don't have the cycles to work through the discussion on it.

**Comment by bvaughn** [comment]
I wasn't trying to say that the "click vs double-click" was a bad decision. I was just asking what the spec was for a few cases that I think are pretty likely to occur.

**Pull request closed without merging**
