### PR TITLE
Don't update current time marker while editing Focus mode

### PR DESCRIPTION
**Pull request by bvaughn**
### [Loom demo](https://www.loom.com/share/959bd0e024364ff3a9bb24646319245c)

cc @jonbell-lot23

### CODE REVIEW

**Comment by jasonLaster** [comment]
@bvaughn looks great

**Comment by jonbell-lot23** [comment]
Hey @bvaughn check out this Loom question: https://www.loom.com/share/b86f1eeeed2646c899cfdfbe04cb8cdf

I think it's important that the red dot always be equal to what we're showing in the seek/video region. Thoughts?

**Comment by bvaughn** [comment]
> I think it's important that the red dot always be equal to what we're showing in the seek/video region. Thoughts?

No, at least I don't agree.

If you're _dragging_ a focus handle– you'll see a preview of where the handle is. (The handle you're dragging is also red.) This is important when you're trying to focus in _around_ a point you're paused at– which is something I do often

The _dot_ is where you're paused at. If that moves when you click to drag, then you _can't_ focus in around a point (because the point would jump as soon as you started dragging). That was our previous UX and it could be pretty annoying in my opinion.

**Comment by jonbell-lot23** [comment]
I agree the dragging dot can be frustrating. But I wonder if we can do anything about the red dot feeling misleading now.

Maybe the red dot can turn blue while dragging? That way we're not claiming that red == current video location during the drag. That would address my concern while not going back to the frustrating behaviour. Would that work?

**Pull request merged**
