### PR TITLE
Replay Next Reconciliation: Moving remaining light/dark items into single variables.css

### PR DESCRIPTION
**Pull request by jonbell-lot23**
As discussed with @bvaughn, I'm queueing up PRs. This PR is combining commits from this one and [the prior one](https://github.com/replayio/devtools/pull/8488).

**Description**
This PR doesn't completely eliminate our old variables.css document, but it comes pretty close. If Delta and Brian don't see anything breaking in the [previous PR](https://github.com/replayio/devtools/pull/8488) or this one, we can push this up to main and consider this part of our migration complete.

Then:

* There are still 85 lines in the old variables document that we'd need to migrate correctly.
* Variables.css still needs better organisation. This PR was just about moving things, optimisation comes next.

### CODE REVIEW

**Comment by jonbell-lot23** [comment]
image

image

Encouraging. As a designer, Delta is my favourite new feature.

**Comment by bvaughn** [comment]
This branch has conflicts, @jonbell-lot23:
> **Conflicting files**
src/devtools/client/themes/variables.css

I'm guessing the PR you merged a few hours ago (#8501) modified overlapping lines in this file. You'll need to manually resolve the conflicts.

**Comment by jonbell-lot23** [comment]
Fixed conflict and should be ready for review.

**Comment by jonbell-lot23** [comment]
I see this lint error but I've run prettier and lint stuff a few times and they keep coming up clean. Not sure what's going wrong there.

**Comment by bvaughn** [comment]
FYI #8505 is going to generate some updated fixture data and may impact this branch. I'll try to push this one over the finish line if it does (and if you want help).

**Comment by bvaughn** [comment]
Looks like Lint's complaining now:
https://github.com/replayio/devtools/actions/runs/3876832150/jobs/6611138858

```
src/devtools/client/themes/variables.css:1:1
 1:1  high  Incorrect formatting, autoformat by running 'trunk fmt'  prettier
```

**Pull request closed without merging**
