### PR TITLE
Scrollbar UI of Element panel improved

### PR DESCRIPTION
**Pull request by Roaster05**
Initially the computed properties were couldn't be viewed completely as there was no scrollbar present

### CODE REVIEW

**Comment by Domiii** [comment]
hi @Roaster05,

I can sense that you are going to be somewhat frustrated by this, but I hope you know why this is happening.

I think the reason why this is happening is because in addition to the other issues I commented on in your first PR, you accidentally conflated previous changes into all following PRs. Do not do that. Always create a new branch -> PR from `main`. Don't do incremental changes because it makes it very hard for us to figure this out.

In case you are not aware of what I'm talking about: I see 19 [files changed](https://github.com/replayio/devtools/pull/8851/files), and a lot of weird random stuff in these changes. No one wants to review or sift through this.

Again, thanks for your hard work. But please spend some time figuring out **all the problems** (and please carefully so) before submitting another one. Also make sure to check your [changed files](https://github.com/replayio/devtools/pull/8851/files) before submitting anything. We don't want to be spammed, so please pay attention to this.

Thank you!

**Comment by Roaster05** [comment]
> hi @Roaster05,
> 
> I can sense that you are going to be somewhat frustrated by this, but I hope you know why this is happening.
> 
> It appears that, in addition to the other issues I commented on in your first PR, you accidentally conflated previous changes into all following PRs. Do not do that. Always create a new branch -> PR from `main`. Don't do incremental changes because it makes it very hard for us to figure this out.
> 
> In case you are not aware of what I'm talking about: I see 19 [files changed](https://github.com/replayio/devtools/pull/8851/files), and a lot of weird random stuff in these changes. No one wants to review or sift through this.
> 
> Again, thanks for your hard work. But please spend some time figuring out **all the problems** (and please carefully so), then **double check** our guidelines and my previous comments here and in the other PR, and only after that, consider submitting another one. Also make sure to check your [changed files](https://github.com/replayio/devtools/pull/8851/files) before submitting anything. We don't want to be spammed, so please pay attention to this.
> 
> Thank you!

I am really sorry i just screwed up i will figure out all the problems and will get back with the same changes again thankyou so much for your review and guidance

**Comment by Roaster05** [comment]
> hi @Roaster05,
> 
> I can sense that you are going to be somewhat frustrated by this, but I hope you know why this is happening.
> 
> It appears that, in addition to the other issues I commented on in your first PR, you accidentally conflated previous changes into all following PRs. Do not do that. Always create a new branch -> PR from `main`. Don't do incremental changes because it makes it very hard for us to figure this out.
> 
> In case you are not aware of what I'm talking about: I see 19 [files changed](https://github.com/replayio/devtools/pull/8851/files), and a lot of weird random stuff in these changes. No one wants to review or sift through this.
> 
> Again, thanks for your hard work. But please spend some time figuring out **all the problems** (and please carefully so), then **double check** our guidelines and my previous comments here and in the other PR, and only after that, consider submitting another one. Also make sure to check your [changed files](https://github.com/replayio/devtools/pull/8851/files) before submitting anything. We don't want to be spammed, so please pay attention to this.
> 
> Thank you!

Hey dormi i am having some issues which i am not able to get off and i would request you if you can help me with those , when i fork my repo and i dont perform any changes then also my 2 tests fail while executing e2e tests using npm run tests also some files get modified automatically like in this particular commit also some files which you can already see are seen as modified files but have the same content and were not altered by me ,i have a bunch of improvements lined up but this error is scratching my head off and i am not able to get rid of these issues .

**Comment by Domiii** [comment]
hi @Roaster05,

1. If tests that are not at all related to your code fail, check if they also fail in other recent PRs. If you see the same tests fail in other recent PRs, then those are likely "work in progress", and probably not at all related to you. You can ignore them in that case.
2. You say "some files get modified automatically". I don't know what you are doing, but there is a good chance, you installed some things in your IDE that does that and you have to configure that right. Please don't ask for help on how to configure your specific IDE here. I cannot help you with that. Feel free to ask in the #gsoc channel on Discord and in other relevant forums instead.

**Pull request closed without merging**
