### PR TITLE
update @replayio/* deps

### PR DESCRIPTION
**Pull request by toshok**
only `@replay/cypress` being updated here, since `/playwright` and `/replay` were already updated.

part of RUN-3159

### CODE REVIEW

**Review by bvaughn — APPROVED** [review]
We don't use Cypress in devtools, so I'm not sure what this is actually doing or being used for. I'd prefer to defer to someone else here for this (@ryanjduffy?)

**Comment by toshok** [comment]
yeah, I see references to cypress in packages/e2e-tests (and imports of that particular @replayio npm package), but I can't trace any of it back to actual usage in our tests.  is there some code to remove?

**Comment by ryanjduffy** [comment]
The dependency can be removed. It was used at one point to generate a recording with cypress for e2e tests but that code was removed so it isn't necessary now.

**Comment by bvaughn** [comment]
Closing in favor of #10259

**Pull request closed without merging**
