### PR TITLE
Removed current time indicator z-index

### PR DESCRIPTION
**Pull request by bvaughn**
PR #7549 added some z-indexes to things in the new Console that caused regressions for the context menu.

I think I've fixed the context menu issue without regressing on the other things #7549 was intended to fix, although the solution is more complex than I wish. Here is a walk-through video showing the console after this change:

https://www.loom.com/share/2a266da80f684699993a543efad61e95

### CODE REVIEW

**Comment by bvaughn** [comment]
Ah, I think I get why this was being done. It was so the border from the error row was visible on both top and bottom (it's red, vs the normal not-red border).

Okay let me re-add z-index for these two things, _and_ the context menu.

**Review by jasonLaster — COMMENTED** [review]
I believe we want to show the pause line at the beginning / end of the logs

**Comment by souporserious** [comment]
@bvaughn yeah, exactly top/bottom! My bad, I should have documented that. We should probably do a z-index audit and get all of those into the design package.

**Comment by bvaughn** [comment]
I need to sort out a small alignment issue with the top border and the current time. I want to add a -1px offset to the current time placement, except that it doesn't work well if it's at the top of the console. Need to sort that out then I'll push an update.

**Comment by bvaughn** [comment]
https://www.loom.com/share/2a266da80f684699993a543efad61e95

**Comment by bvaughn** [comment]
I am going to add playwright tests for this now.

**Pull request merged**
