### PR TITLE
Polish test info UI

### PR DESCRIPTION
**Pull request by jaril**

### CODE REVIEW

**Comment by jaril** [comment]
@jonbell-lot23 🙋‍♂️

**Comment by jonbell-lot23** [comment]
About to address some lint errors, stand by...

**Comment by jonbell-lot23** [comment]
I ended up with a strange branch/merge situation that I can't resolve. If someone else can please fix the lint errors and merge, I'd appreciate it.

**Comment by ryanjduffy** [comment]
@jonbell-lot23 fixed up the linting and merge. Landing as soon as it's green

**Pull request merged**
