### PR TITLE
Add an animated drawer to testsuites' step details

### PR DESCRIPTION
**Pull request by jonbell-lot23**
Loom demonstration: https://www.loom.com/share/2a6b48dc908a4eba8d15b45d1bc66ddf

Quick gif:
Step Details Drawer

### CODE REVIEW

**Comment by jonbell-lot23** [comment]
Addresses SCS-486

**Comment by jaril** [comment]
@jonbell-lot23 moving to a different sidebar panel (comments) resets the expand/collapse state. Mind fixing that?

**Comment by jonbell-lot23** [comment]
> @jonbell-lot23 moving to a different sidebar panel (comments) resets the expand/collapse state. Mind fixing that?

Yup!

**Comment by jonbell-lot23** [comment]
Ok @jaril or @ryanjduffy I'm using localstorage to track the state of the drawer.

**Review by ryanjduffy — APPROVED** [review]

**Pull request merged**
