### PR TITLE
Stop using the astLocation

### PR DESCRIPTION
**Pull request by jasonLaster**

### CODE REVIEW

**Comment by markerikson** [comment]
What's the driver for this change?

**Comment by jcmorrow** [comment]
@markerikson see https://linear.app/replay/issue/FE-698/[glide]-invalidlocation

**Review by jcmorrow — APPROVED** [review]
OK, now that I understand this, 💯 approve!

**Comment by markerikson** [comment]
Oh sure, yeah! One less bit of complexity 🎉

**Review by markerikson — APPROVED** [review]

**Pull request merged**
